comics/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from comics.views import IndexView, SeriesView, IssueView, CharacterView, ArcView, \
    TeamView, PublisherView, CreatorView, IssueUpdateView, IssueDeleteView, \
    ServerSettingsView, read, importer, reprocess, update_issue_status

from . import views

app_name = 'comics'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^series/(?P<slug>[\w\-]+)/$', SeriesView.as_view(), name='series'),
    url(r'^issue/(?P<slug>[\w\-]+)/$', IssueView.as_view(), name='issue'),
    url(r'^issue/(?P<slug>[\w\-]+)/read$', read, name='read'),
    url(r'^issue/(?P<slug>[\w\-]+)/update-status$',
        update_issue_status, name='update_issue_status'),
    url(r'^character/(?P<slug>[\w\-]+)/$',
        CharacterView.as_view(), name='character'),
    url(r'^arc/(?P<slug>[\w\-]+)/$', ArcView.as_view(), name='arc'),
    url(r'^team/(?P<slug>[\w\-]+)/$', TeamView.as_view(), name='team'),
    url(r'^publisher/(?P<slug>[\w\-]+)/$',
        PublisherView.as_view(), name='publisher'),
    url(r'^creator/(?P<slug>[\w\-]+)/$', CreatorView.as_view(), name='creator'),
    url('importer', importer, name='importer'),
    url(r'^issue/(?P<slug>[\w\-]+)/update/$',
        IssueUpdateView.as_view(), name='issue-update'),
    url(r'^issue/(?P<slug>[\w\-]+)/delete/$',
        IssueDeleteView.as_view(), name='issue-delete'),
    url(r'^issue/(?P<slug>[\w\-]+)/reprocess$',
        reprocess, name='reprocess'),
    url(r'^server-settings', ServerSettingsView.as_view(), name='server-settings'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tenma/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from comics import views
from rest_framework import routers
from rest_framework.schemas import get_schema_view

router = routers.DefaultRouter()
router.register(r'arcs', views.ArcViewSet)
router.register(r'characters', views.CharacterViewSet)
router.register(r'creators', views.CreatorViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'issues', views.IssueViewSet)
router.register(r'publishers', views.PublisherViewSet)
router.register(r'series', views.SeriesViewSet)
router.register(r'settings', views.SettingsViewSet)
router.register(r'teams', views.TeamViewSet)
router.register(r'users', views.UserViewSet)

schema_view = get_schema_view(title='Tenma API')

urlpatterns = [
	url('^v1/schema/$', schema_view),
	url(r'', include('comics.urls')),
	url(r'^v1/', include(router.urls)),
	url(r'^admin/', admin.site.urls),
	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

comics/models.py
from __future__ import unicode_literals

import datetime
import os
import rarfile
import zipfile
import tarfile

from shutil import copyfile
from multiselectfield import MultiSelectField

from django.db import models
from solo.models import SingletonModel
from django.utils import timezone
from django.conf import settings
from django.core.validators import RegexValidator

from .utils.comicfilehandler import ComicFileHandler

"""
Choices for model use.
"""
# Generated years
YEAR_CHOICES = [(r, r) for r in range(1837, datetime.date.today().year + 1)]

# Comic read status
STATUS_CHOICES = (
    (0, 'Unread'),
    (1, 'Partially read'),
    (2, 'Completed'),
)

# Creator roles for an issue
ROLE_CHOICES = (
    ('artist', 'Artist'),
    ('colorist', 'Colorist'),
    ('cover', 'Cover'),
    ('editor', 'Editor'),
    ('inker', 'Inker'),
    ('journalist', 'Journalist'),
    ('letterer', 'Letterer'),
    ('other', 'Other'),
    ('penciler', 'Penciler'),
    ('production', 'Production'),
    ('writer', 'Writer'),
)


class Settings(SingletonModel):
    api_key = models.CharField(
        'ComicVine API Key',
        help_text="A 40-character key provided by ComicVine. This is used to retrieve metadata about your comics. You can create a ComicVine API Key at <a target=\"_blank\" href=\"http://comicvine.gamespot.com/api/\">ComicVine's API Page</a> (ComicVine account is required).",
        validators=[RegexValidator(
            regex='^.{40}$',
            message='Length must be 40 characters.',
            code='nomatch'
        )],
        max_length=40,
        blank=True
    )

    def __str__(self):
        return "Settings"


class Arc(models.Model):
    cvid = models.CharField(max_length=15)
    cvurl = models.URLField(max_length=200)
    name = models.CharField('Arc name', max_length=200)
    desc = models.TextField('Description', max_length=500, blank=True)
    image = models.FilePathField(
        'Image file path', path="media/images", blank=True)

    def __str__(self):
        return self.name


class Team(models.Model):
    cvid = models.CharField(max_length=15)
    cvurl = models.URLField(max_length=200)
    name = models.CharField('Team name', max_length=200)
    desc = models.TextField('Description', max_length=500, blank=True)
    image = models.FilePathField(
        'Image file path', path="media/images", blank=True)

    def __str__(self):
        return self.name


class Character(models.Model):
    cvid = models.CharField(max_length=15)
    cvurl = models.URLField(max_length=200)
    name = models.CharField('Character name', max_length=200)
    desc = models.TextField('Description', max_length=500, blank=True)
    teams = models.ManyToManyField(Team, blank=True)
    image = models.FilePathField(
        'Image file path', path="media/images", blank=True)

    def __str__(self):
        return self.name


class Creator(models.Model):
    cvid = models.CharField(max_length=15)
    cvurl = models.URLField(max_length=200)
    name = models.CharField('Creator name', max_length=200)
    desc = models.TextField('Description', max_length=500, blank=True)
    image = models.FilePathField(
        'Image file path', path="media/images", blank=True)

    def __str__(self):
        return self.name


class Publisher(models.Model):
    cvid = models.CharField(max_length=15)
    cvurl = models.URLField(max_length=200)
    name = models.CharField('Series name', max_length=200)
    desc = models.TextField('Description', max_length=500, blank=True)
    logo = models.FilePathField(
        'Logo file path', path="media/images", blank=True)

    def __str__(self):
        return self.name


class Series(models.Model):
    cvid = models.CharField(max_length=15, blank=True)
    cvurl = models.URLField(max_length=200, blank=True)
    name = models.CharField('Series name', max_length=200)
    publisher = models.ForeignKey(
        Publisher, on_delete=models.CASCADE, null=True, blank=True)
    year = models.PositiveSmallIntegerField(
        'year', choices=YEAR_CHOICES, default=datetime.datetime.now().year, blank=True)
    desc = models.TextField('Description', max_length=500, blank=True)

    def __str__(self):
        return self.name

    def issue_numerical_order_set(self):
        return self.issue_set.all().order_by('number')

    def issue_count(self):
        return self.issue_set.all().count()

    def unread_issue_count(self):
        return self.issue_set.exclude(status=2).count()

    class Meta:
        verbose_name_plural = "Series"


class Issue(models.Model):
    cvid = models.CharField('ComicVine ID', max_length=15, blank=True)
    cvurl = models.URLField(max_length=200, blank=True)
    series = models.ForeignKey(Series, on_delete=models.CASCADE, blank=True)
    name = models.CharField('Issue name', max_length=200, blank=True)
    number = models.CharField('Issue number', max_length=25)
    date = models.DateField('Cover date', blank=True)
    desc = models.TextField('Description', max_length=500, blank=True)
    arcs = models.ManyToManyField(Arc, blank=True)
    characters = models.ManyToManyField(Character, blank=True)
    teams = models.ManyToManyField(Team, blank=True)
    file = models.FilePathField('File path', path="files/", recursive=True)
    cover = models.FilePathField(
        'Cover file path', path="media/images", blank=True)
    status = models.PositiveSmallIntegerField(
        'Status', choices=STATUS_CHOICES, default=0, blank=True)
    leaf = models.PositiveSmallIntegerField(
        editable=False, default=1, blank=True)
    page_count = models.PositiveSmallIntegerField(
        editable=False, default=1, blank=True)

    def __str__(self):
        return self.series.name + ' #' + str(self.number)

    def get_absolute_url(self):
        return reverse('author-detail', kwargs={'pk': self.pk})

    def page_set(self):
        comicfilehandler = ComicFileHandler()
        comic = comicfilehandler.extract_comic(self.file, self.id)

        return comic


class Roles(models.Model):
    creator = models.ForeignKey(Creator, on_delete=models.CASCADE)
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    roles = MultiSelectField(choices=ROLE_CHOICES)

    def __str__(self):
        return self.issue.series.name + ' #' + str(self.issue.number) + ' - ' + self.creator.name

    class Meta:
        verbose_name_plural = "Roles"

comics/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.http import HttpResponseRedirect, JsonResponse
from .models import Series, Issue, Character, Arc, Team, Publisher, Creator, Settings, Roles
from .tasks import import_comic_files_task, reprocess_issue_task
from .utils.comicimporter import ComicImporter

class IndexView(ListView):
	template_name = 'comics/index.html'
	context_object_name = 'all_series'

	def get_queryset(self):
		return Series.objects.order_by('name')

class SeriesView(DetailView):
	model = Series
	template_name = 'comics/series.html'

class IssueView(DetailView):
	model = Issue
	template_name = 'comics/issue.html'

	def get_context_data(self, **kwargs):
		context = super(IssueView, self).get_context_data(**kwargs)
		issue = self.get_object()
		context['roles_list'] = Roles.objects.filter(issue=issue)
		return context

class CharacterView(DetailView):
	model = Character
	template_name = 'comics/character.html'

	def get_context_data(self, **kwargs):
		context = super(CharacterView, self).get_context_data(**kwargs)
		character = self.get_object()
		context['issue_list'] = character.issue_set.all().order_by('series__name', 'number')
		return context

class ArcView(DetailView):
	model = Arc
	template_name = 'comics/arc.html'

	def get_context_data(self, **kwargs):
		context = super(ArcView, self).get_context_data(**kwargs)
		arc = self.get_object()
		context['issue_list'] = arc.issue_set.all().order_by('series__name', 'number')
		return context

class TeamView(DetailView):
	model = Team
	template_name = 'comics/team.html'

	def get_context_data(self, **kwargs):
		context = super(TeamView, self).get_context_data(**kwargs)
		team = self.get_object()
		context['issue_list'] = team.issue_set.all().order_by('series__name', 'number')
		return context

class PublisherView(DetailView):
	model = Publisher
	template_name = 'comics/publisher.html'

class CreatorView(DetailView):
	model = Creator
	template_name = 'comics/creator.html'

	def get_context_data(self, **kwargs):
		context = super(CreatorView, self).get_context_data(**kwargs)
		creator = self.get_object()
		roles = Roles.objects.filter(creator=creator)
		context['issue_list'] = Issue.objects.filter(id__in=roles.values('issue_id'))
		return context

class ServerSettingsView(UpdateView):
	model = Settings
	fields = '__all__'
	template_name = 'comics/server_settings.html'

	def get_object(self, *args, **kwargs):
		return Settings.get_solo()

	def form_valid(self, form):
		self.object = form.save()
		return render(self.request, 'comics/server-settings-success.html', {'server-settings': self.object})

class IssueUpdateView(UpdateView):
	model = Issue
	fields = ['cvid']
	template_name = 'comics/issue_update.html'

	def form_valid(self, form):
		self.object = form.save()
		return render(self.request, 'comics/issue_update_success.html', {'issue-update': self.object})

class IssueDeleteView(DeleteView):
	model = Issue
	success_url = '/'

def read(request, slug):
	issue = get_object_or_404(Issue, slug=slug)
	return render(request, 'comics/read.html', {'issue': issue})

def importer(request):
	import_comic_files_task.delay()
	return HttpResponseRedirect('/')

def reprocess(request, slug):
	reprocess_issue_task.delay(slug)
	return HttpResponseRedirect('/issue/' + slug)

def update_issue_status(request, slug):
	issue = Issue.objects.get(slug=slug)

	if request.GET.get('complete', '') == '1':
		issue.leaf = 1
		issue.status = 2
		issue.save()
	else:
		issue.leaf = int(request.GET.get('leaf', ''))
		issue.status = 1
		issue.save()

	data = { 'saved': 1 }

	return JsonResponse(data)

comics/templates/comics/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tenma</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'comics/tenma-favicon.png' %}"/>
        <link rel="stylesheet" href="{% static 'comics/flexslider/flexslider.css' %}" type="text/css">
        <link rel="stylesheet" type="text/css" href="{% static 'comics/style.css' %}" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://malsup.github.io/jquery.form.js"></script>
        <script src="https://use.fontawesome.com/d3455c4c52.js"></script>
        <script src="{% static 'comics/bootstrap/bootstrap.min.js' %}"></script>
        <script src="{% static 'comics/flexslider/jquery.flexslider-min.js' %}"></script>
        <script src="{% static 'comics/script.js' %}"></script>
    </head>

    <body class="{% block page-type %}{% endblock %}">
        <header>
            <div id="navbar">
                <a class="logo" href="/"><img src="{% static 'comics/tenma-logo.png' %}"></a>
                {% block menu %}
                    <a data-toggle="modal" data-target="#modal"><i class="settings-button fa fa-cog"></i></a>
                {% endblock %}
            </div>
        </header>

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </body>

    <footer>
        <div class="metadata-disclaimer">
            <div class="text">
                <p>Metadata on this page is retrieved from </p>
            </div>
            <div class="logo">
                <a target="_blank" href="http://comicvine.gamespot.com"><img src ="{% static 'comics/comicvine_logo.png' %}"></a>
            </div>
        </div>
    </footer>

    <div class="modal" id="modal"></div>

    <script>
        $('.settings-button').on('click', function (event) {
            var modal = $('#modal')
            $.ajax({
                url: "{% url 'comics:server-settings' %}",
                context: document.body
            }).done(function(response) {
                modal.html(response);
            });
        })
    </script>
</html>

comics/templates/comics/index.html
{% extends "comics/base.html" %}

{% load simple_crop %}

{% block page-title %}{{ series.name }}{% endblock page-title %}

{% block content %}

<div class="series-filter-wrapper">
	<i class="fa fa-search"></i>
	<input id="series-filter" type="text">
</div>

<div class="all-series">
{% if all_series %}
	<ul>
		{% for series in all_series %}
			{% if series.issue_set.all %}
			<li>
				<a href="{% url 'comics:series' series.slug %}">
					<img src="{{ series.issue_numerical_order_set.first.cover|smartcrop:"1280x1950"|urlencode }}" alt = "{{ series.name }}" >
					{% if series.unread_issue_count > 0 %}
						<div class="unread-count">
							<p>{{ series.unread_issue_count }}</p>
						</div>
					{% endif %}
				</a>
				<a href="{% url 'comics:series' series.slug %}"><p>{{ series.name }}</p></a>
			</li>
			{% endif %}
		{% endfor %}
	</ul>
{% else %}
	<div class="no-series">
		<p>No series currently available.</p>
	</div>
{% endif %}
	<div class="no-results">
		<p>No series match your search.</p>
	</div>
</div>

{% endblock content %}

comics/templates/comics/issue.html
{% extends "comics/base.html" %}

{% block content %}

<div class="issue-info-wrapper">
	{% if issue.cover|length %}
	<div class="issue-cover">
		<div class="issue-cover-image">
			{% autoescape off %}
			<img src="/{{ issue.cover|urlencode }}" >
			{% endautoescape %}
			<div class="issue-cover-overlay">
				<a href="{% url 'comics:read' issue.slug %}">
					<i class="read-button fa fa-eye"></i>
				</a>
				<a data-toggle="modal" data-target="#modal" href="{% url 'comics:issue-update' issue.slug %}">
					<i class="issue-update-button fa fa-pencil"></i>
				</a>
			</div>
		</div>
	</div>
	{% endif %}
	<div class="issue-info">
		<div class="issue-title">
			{% if issue.series.name %}
			<h1>{{ issue.series.name }}</h1>
			{% endif %}
			<h3>Issue #{{ issue.number }}{% if issue.name %} - <i>{{ issue.name }}</i>{% endif %}</h3>
			{% if issue.date %}
			<p>Released: {{ issue.date }}</p>
			{% endif %}
			<p>{{ issue.page_count }} pages</p>
			<form action="{% url 'comics:issue-delete' issue.slug %}" method="post">{% csrf_token %}
				<input type="submit" name="remove-issue" value="Remove">
			</form>
		</div>

		{% include "comics/related_arcs.html" with arc_list=issue.arcs.all %}

		{% if issue.desc %}
		{% autoescape off %}
		<div class="issue-description">
			<p>{{ issue.desc|truncatewords:180 }}</p>
		</div>
		{% endautoescape %}
		{% endif %}

		{% include "comics/comicvine_link.html" with cvurl=issue.cvurl %}

	</div>
</div>

{% include "comics/related_publisher.html" with publisher=issue.series.publisher %}

{% include "comics/related_characters.html" with character_list=issue.characters.all %}

{% include "comics/related_creators.html" with roles_list=roles_list.all %}

{% include "comics/related_teams.html" with team_list=issue.teams.all %}
<script>
    $('.issue-update-button').on('click', function (event) {
        var modal = $('#modal')
        $.ajax({
            url: "{% url 'comics:issue-update' issue.slug %}",
            context: document.body
        }).done(function(response) {
            modal.html(response);
        });
    })
</script>
{% endblock content %}

comics/templates/comics/issue_update.html
{% load widget_tweaks %}
<div class="modal-dialog modal-lg" role="document">
	<form action="{% url 'comics:issue-update' issue.slug %}" method="post" id="issue-update" class="form">{% csrf_token %}
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="modal-title">Edit Issue</h3>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<i class="close-settings fa fa-times-circle"></i>
				</button>
			</div>
			<div class="modal-body">
				<a class="reprocess-issue button" href="{% url 'comics:reprocess' issue.slug %}">Reprocess</a>
				<p class="helptext">Use the reprocess button to reprocess this issue's metadata from ComicVine.</p>
				{{ form.media }}
				{% for field in form.visible_fields %}
					{{ field.errors }}
					{{ field.label_tag }}
					{{ field|attr:"class:form-control" }}
					<p class="helptext">{{ field.help_text|safe }}</p>
				{% endfor %}
			</div>
			<div class="modal-footer">
				<input type="submit" class="btn btn-primary" value="Save changes" />
			</div>
		</div><!-- /.modal-content -->
	</form>
</div><!-- /.modal-dialog -->
<script>
    var form_options = { target: '#modal', success: function(response) {} };
    $('#issue-update').ajaxForm(form_options);
</script>

comics/templates/comics/read.html
{% extends "comics/base.html" %}
{% load staticfiles %}

{% block menu %}
	<div class="reader-controls">
		<div class="fit-vertically button">
			<i class="fa fa-arrows-v"></i><p>Fit Vertically</p>
		</div>
		<div class="fit-horizontally button">
			<i class="fa fa-arrows-h"></i><p>Fit Horizontally</p>
		</div>
		<div class="page-count">
			<p><span class="current-page">1</span> / <span class="page-total"></span></p>
		</div>
	</div>
{% endblock %}

{% block page-type %}reader{% endblock %}

{% block content %}

<div class="flexslider reader-slider">
	<div class="issue-data" data-id="{{ issue.slug }}" data-leaf="{{ issue.leaf }}"></div>
	<ul class="slides">
		{% for item in issue.page_set.pages %}
		{% with mediaurl=issue.page_set.mediaurl %}
		<li class="page page-{{ forloop.counter }}">
			<img src="{% static 'comics/image-loading.png' %}" data-source="{{ mediaurl }}{{ item }}" class="lazy-load" alt="Page #{{ forloop.counter }}" >
		</li>
		{% endwith %}
		{% endfor %}
	</ul>
</div>

{% endblock content %}

comics/templates/comics/related_arcs.html
{% if arc_list %}
<div class="story-arcs">
	{% for arc in arc_list %}

		{% if forloop.first %}
			<p>Story arc{{ arc_list|pluralize }}: 
		{% endif %}

		<a href="{% url 'comics:arc' arc.slug %}"><i><u>{{ arc.name }}</u></i></a>

		{% if not forloop.last %}
			,
		{% endif %}

		{% if forloop.last %}
			</p>
		{% endif %}

	{% endfor %}
</div>
{% endif %}

comics/templates/comics/related_characters.html
{% load simple_crop %}
{% load staticfiles %}

{% if character_list %}
<div class="related related-characters">
	<h2>Characters</h2>
	<div class="flexslider related-slider">
		<ul class="slides">
			{% for character in character_list %}
			<li>
				<a href="{% url 'comics:character' character.slug %}">
					<div class="image">
						{% if character.image %}
							<img src="{{ character.image|smartcrop:"200x305"|urlencode }}" alt="{{ character.name }}" >
						{% else %}
							<img src="{% static 'comics/image-not-found.png' %}" alt="{{ character.name }}" >
						{% endif %}
					</div>
				</a>
				<a href="{% url 'comics:character' character.slug %}"><p>{{ character.name }}</p></a>
			</li>
			{% endfor %}
		</ul>
	</div>
</div>
{% endif %}

comics/templates/comics/related_creators.html
{% load simple_crop %}
{% load staticfiles %}

{% if roles_list %}
<div class="related related-creators">
	<h2>Creators</h2>
	<div class="flexslider related-slider">
		<ul class="slides">
			{% for roles in roles_list %}
			<li>
				<a href="{% url 'comics:creator' roles.creator.slug %}">
					<div class="image">
					{% if roles.creator.image %}
						<img src="{{ roles.creator.image|smartcrop:"200x305"|urlencode }}" alt="{{ roles.creator.name }}" >
					{% else %}
						<img src="{% static 'comics/image-not-found.png' %}" alt="{{ roles.creator.name }}" >
					{% endif %}
					</div>
				</a>
				<a href="{% url 'comics:creator' roles.creator.id %}"><p>{{ roles.creator.name }}</p></a>
				<p><small><em>{{ roles.roles }}</em></small></p>
			</li>
			{% endfor %}
		</ul>
	</div>
</div>
{% endif %}

comics/templates/comics/related_issues.html
{% load simple_crop %}
{% load staticfiles %}

{% if issue_list %}
<div class="related related-issues">
	<h2>Issues</h2>
	<div class="flexslider related-slider">
		<ul class="slides">
			{% for issue in issue_list %}
			<li>
				<a href="{% url 'comics:issue' issue.slug %}">
					<div class="image">
						{% if issue.cover %}
							<img src="{{ issue.cover|smartcrop:"200x305"|urlencode }}" alt = "{{ series.name }}" >
						{% else %}
							<img src="{% static 'comics/image-not-found.png' %}" alt="{{ series.name }}" >
						{% endif %}
						{% if issue.status == 0 %}
							<i class="fa fa-circle fa-2x"></i>
						{% elif issue.status == 1 %}
							<i class="fa fa-adjust fa-2x fa-flip-horizontal"></i>
						{% endif %}
					</div>
				</a>
				<a href="{% url 'comics:issue' issue.slug %}"><p>Issue #{{ issue.number }}</p></a>
			</li>
			{% endfor %}
		</ul>
	</div>
</div>
{% endif %}

comics/templates/comics/related_publisher.html
{% if publisher %}
<div class="related-publisher">
	<a href="{% url 'comics:publisher' publisher.slug %}">
		{% if publisher.logo|length %}
			<img src="/{{ publisher.logo|urlencode }}" alt = "{{ publisher.name }}" >
		{% else %}
			<i>Published by: <u>{{ publisher.name }}</u></i>
		{% endif %}
	</a>
</div>
{% endif %}

comics/templates/comics/related_series.html
{% load simple_crop %}
{% load staticfiles %}

<div class="related related-series">
	<h2>Series</h2>
	<div class="flexslider related-slider">
		<ul class="slides">
			{% for series in allseries %}
			<li>
				<a href="{% url 'comics:series' series.slug %}">
					<div class="image">
						{% if series.issue_numerical_order_set.first.cover %}
							<img src="{{ series.issue_numerical_order_set.first.cover|smartcrop:"200x305"|urlencode }}" alt="{{ seriesname }}" >
						{% else %}
							<img src="{% static 'comics/image-not-found.png' %}" alt="{{ seriesname }}" >
						{% endif %}
					</div>
				</a>
				<a href="{% url 'comics:series' series.id %}"><p>{{ series.name }}</p></a>
			</li>
			{% endfor %}
		</ul>
	</div>
</div>

comics/templates/comics/related_teams.html
{% load simple_crop %}
{% load staticfiles %}

{% if team_list %}
<div class="related related-teams">
	<h2>Teams</h2>
	<div class="flexslider related-slider">
		<ul class="slides">
			{% for team in team_list %}
			<li>
				<a href="{% url 'comics:team' team.slug %}">
					<div class="image">
						{% if team.image %}
							<img src="{{ team.image|smartcrop:"200x305"|urlencode }}" alt="{{ team.name }}" >
						{% else %}
							<img src="{% static 'comics/image-not-found.png' %}" alt="{{ team.name }}" >
						{% endif %}
					</div>
				</a>
				<a href="{% url 'comics:team' team.id %}"><p>{{ team.name }}</p></a>
			</li>
			{% endfor %}
		</ul>
	</div>
</div>
{% endif %}